In [46]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


# from google.colab import files
# uploaded = files.upload()

In [47]:
df = pd.read_csv('LBW_Dataset.csv')

In [48]:
df

Community   Age  Weight  ...  Education  Residence  Result
0           1  21.0    42.0  ...        5.0        1.0       0
1           1  21.0     NaN  ...        5.0        1.0       0
2           1  21.0     NaN  ...        5.0        1.0       0
3           1  21.0     NaN  ...        5.0        1.0       0
4           1  24.0    33.0  ...        5.0        1.0       0
..        ...   ...     ...  ...        ...        ...     ...
91          3  21.0    55.0  ...        5.0        1.0       1
92          3  24.0    39.0  ...        5.0        1.0       1
93          3   NaN    50.0  ...        NaN        1.0       1
94          1   NaN    38.0  ...        5.0        1.0       1
95          3  21.0    50.0  ...        5.0        1.0       1

[96 rows x 10 columns]

In [49]:
number_of_null_values_per_col = df.isnull().sum(axis=0)

number_of_null_values_per_col

Community          0
Age                7
Weight            11
Delivery phase     4
HB                19
IFA                0
BP                15
Education          3
Residence          2
Result             0
dtype: int64

In [50]:
# look at the # of missing points in the second, third, fourth and fifth columns
number_of_null_values_per_col[1:5]

Age                7
Weight            11
Delivery phase     4
HB                19
dtype: int64

## How many cells of data points are missing?

In [51]:
total_no_of_cells = np.product(df.shape)
total_no_of_missing_cells = number_of_null_values_per_col.sum()

percent_missing_cells = (total_no_of_missing_cells / total_no_of_cells)

print(f"Percentage of data cells that is missing is: {percent_missing_cells:.4%}")

Percentage of data cells that is missing is: 6.3542%


## Which column has the most number of missing values?

In [52]:
print(number_of_null_values_per_col.idxmax(), number_of_null_values_per_col.max())

HB 19


In [53]:
#Analyse each column and checkout diff things from here

In [54]:
#Education - All 5 - Scam
df["Education"].fillna(5, inplace=True)
df["Education"].unique()

array([5.])

In [55]:
#Residence - use mode to replace it
df["Residence"].fillna(df.Residence.mode()[0], inplace=True)
df["Residence"].unique()

array([1., 2.])

In [56]:
#Delivery Phase - use mode to replace
df["Delivery phase"].fillna(df["Delivery phase"].mode()[0], inplace=True)
df["Delivery phase"].unique()

array([1., 2.])

In [57]:
df.groupby('Result').transform('mean')

Community        Age     Weight  ...        BP  Education  Residence
0    2.083333  23.818182  36.000000  ...  1.775443        5.0   1.083333
1    2.083333  23.818182  36.000000  ...  1.775443        5.0   1.083333
2    2.083333  23.818182  36.000000  ...  1.775443        5.0   1.083333
3    2.083333  23.818182  36.000000  ...  1.775443        5.0   1.083333
4    2.083333  23.818182  36.000000  ...  1.775443        5.0   1.083333
..        ...        ...        ...  ...       ...        ...        ...
91   2.208333  23.731343  46.777778  ...  1.711841        5.0   1.152778
92   2.208333  23.731343  46.777778  ...  1.711841        5.0   1.152778
93   2.208333  23.731343  46.777778  ...  1.711841        5.0   1.152778
94   2.208333  23.731343  46.777778  ...  1.711841        5.0   1.152778
95   2.208333  23.731343  46.777778  ...  1.711841        5.0   1.152778

[96 rows x 9 columns]

In [58]:
#Use Mean-By-Output-Class for "Weight, Age, HB, BP"
df = df.fillna(df.groupby('Result').transform('mean')) 

In [59]:
#Check Weight
df["Weight"].unique()

array([42., 36., 33., 35., 31., 30., 38., 32., 39., 45., 40., 49., 48.,
       60., 37., 50., 65., 55., 43., 64., 52., 54., 46., 62., 41., 51.,
       44., 56., 63.])

In [60]:
#Check Age
df["Age"].unique()

array([21.        , 24.        , 26.        , 22.        , 17.        ,
       35.        , 20.        , 38.        , 23.        , 25.        ,
       23.81818182, 27.        , 23.73134328, 28.        , 18.        ,
       29.        ])

In [61]:
#Cheeck HB
df["HB"].unique()

array([ 9.2       ,  8.8       ,  8.        ,  9.3       ,  9.09375   ,
        9.        ,  9.9       , 10.        ,  8.9       ,  9.6       ,
        9.4       ,  8.7       ,  9.5       ,  9.07213115,  9.1       ,
        8.4       ,  6.2       , 10.9       ,  7.9       , 10.8       ,
       10.2       , 10.4       , 11.        ,  5.9       ])

In [62]:
#Check BP
df["BP"].unique()

array([ 1.375     ,  1.5       ,  2.125     ,  1.571     ,  1.57142857,
        1.625     ,  1.77544344,  1.71428571,  1.2       ,  5.5       ,
        1.66153846,  1.33333333,  1.333     ,  1.714     ,  1.666     ,
        1.83333333,  1.66666667,  2.5       , 13.875     ,  1.22222222,
        1.42857143,  1.71184053])

In [63]:
df.isnull().sum(axis = 0)

Community         0
Age               0
Weight            0
Delivery phase    0
HB                0
IFA               0
BP                0
Education         0
Residence         0
Result            0
dtype: int64

In [64]:
df

Community        Age  Weight  ...  Education  Residence  Result
0           1  21.000000    42.0  ...        5.0        1.0       0
1           1  21.000000    36.0  ...        5.0        1.0       0
2           1  21.000000    36.0  ...        5.0        1.0       0
3           1  21.000000    36.0  ...        5.0        1.0       0
4           1  24.000000    33.0  ...        5.0        1.0       0
..        ...        ...     ...  ...        ...        ...     ...
91          3  21.000000    55.0  ...        5.0        1.0       1
92          3  24.000000    39.0  ...        5.0        1.0       1
93          3  23.731343    50.0  ...        5.0        1.0       1
94          1  23.731343    38.0  ...        5.0        1.0       1
95          3  21.000000    50.0  ...        5.0        1.0       1

[96 rows x 10 columns]

In [65]:
def get_entropy_of_dataset(df):
    # gets the target column
    target = df.loc[:, df.columns[-1]]
    unique_values = target.unique().tolist()

    # number of unique values
    uniq = len(unique_values)

    target = target.tolist()
    vals = []
    for i in range(uniq):
        vals.append(target.count(unique_values[i]))
    summ = sum(vals)
    entropy = 0
    for i in range(uniq):
        entropy += (-1)*(vals[i]/summ)*(np.log2(vals[i]/summ))
    return entropy

In [66]:
def entropyFormula(answerDict):
    valueOfAttribute_entropy = {}

    for value in answerDict:
        temp = answerDict[value].values()
        denominator = sum(temp)
        entropy = 0

        for count in temp:
            if (count != 0):
                entropy += -(count/denominator) * np.log2(count/denominator)

        valueOfAttribute_entropy[value] = entropy

    return valueOfAttribute_entropy

In [67]:
def avgInformationEntropy(answerDict, valueOfAttribute_entropy,
                          totalNumberOfSamples):
    answer = 0
    for valueOfAttribute in answerDict:
        numerator = sum(answerDict[valueOfAttribute].values())
        answer += numerator / totalNumberOfSamples * \
            valueOfAttribute_entropy[valueOfAttribute]

    return answer

In [68]:
def get_entropy_of_attribute(df, attribute):
    entropy_of_attribute = 0

    if attribute not in df.columns.tolist():
        return entropy_of_attribute

    # Get the name of the target attribute column
    TARGET_ATTRIBUTE = df.columns.tolist()[-1]

    # Get the list of unique values the attribute can take
    valuesOfAttribute = df[attribute].unique().tolist()

    # Get the list of unique values the TARGET_ATTRIBUTE can take
    valuesOfTargetAttribute = df[TARGET_ATTRIBUTE].unique().tolist()

    # Create a dictionary containing the values of attribute as keys
    # and the values as the outcome:no_of_occurrences
    # E.g.:
    # {
    # 	'val1': {'a':1, 'b':0},
    # 	'val2': {'a':0, 'b':2}
    # }
    answerDict = {}
    for value in valuesOfAttribute:
        answerDict[value] = dict.fromkeys(valuesOfTargetAttribute, 0)

    # print(answerDict)

    # Create a dictionary to hold the unique attribute value with the
    # corresponding df as key-value pairs
    valuesOfAttribute_Dataframe = {}

    # Fill in the values in to the: valuesOfAttribute_Dataframe, dictionary
    for value in valuesOfAttribute:
        valuesOfAttribute_Dataframe[value] = df.loc[df[attribute] == value]

    # For each dataframe
    for valueOfAttribute in valuesOfAttribute_Dataframe:
        dataframe = valuesOfAttribute_Dataframe[valueOfAttribute]

        for valueOfTargetAttribute in valuesOfTargetAttribute:
            # Find to the count of different entries in the target attribute
            temp = dataframe.loc[dataframe[TARGET_ATTRIBUTE] ==
                                 valueOfTargetAttribute] \
                .count().tolist()[-1]

            answerDict[valueOfAttribute][valueOfTargetAttribute] = temp

    # print(answerDict)

    # Use the entropy formula and get the entropy of all the attribute
    # value pairs and take the sum
    valueOfAttribute_entropy = entropyFormula(answerDict)
    entropy_of_attribute = avgInformationEntropy(answerDict,
                                                 valueOfAttribute_entropy,
                                                 df.shape[0])

    # 3. Return the sum
    return abs(entropy_of_attribute)

In [69]:
def get_information_gain(df, attribute):
    return abs(get_entropy_of_dataset(df) - get_entropy_of_attribute(df, attribute))

In [70]:
#Find IG for each column
information_gains = dict()
for i in df.columns.tolist():
  information_gains[i] = get_information_gain(df, i)

In [71]:
get_entropy_of_dataset(df)

0.8112781244591328

In [72]:
information_gains

{'Age': 0.14411172983242193,
 'BP': 0.3664469842305207,
 'Community': 0.0069157923437370705,
 'Delivery phase': 0.004430399630443338,
 'Education': 0.0,
 'HB': 0.3385844780014577,
 'IFA': 0.022873345732139616,
 'Residence': 0.006093039758486074,
 'Result': 0.8112781244591328,
 'Weight': 0.5710535508362805}

In [73]:
assert information_gains['Result'] == get_entropy_of_dataset(df), "Information Gain of the 'Result' Column must be equal to the entropy of the 'Result' Column"

In [74]:
assert information_gains['Education'] == 0.0, "Information Gain of the 'Education' Column must be equal to 0 as it has only one type of value (i.e. 5.0) in the entire dataset"

In [75]:
max_IG = max(information_gains.values())
for i in df.columns.tolist():
  if(information_gains[i] < 0.3*max_IG):
    print(f"{i} column is dropped")
    del df[i]

Community column is dropped
Age column is dropped
Delivery phase column is dropped
IFA column is dropped
Education column is dropped
Residence column is dropped


In [76]:
df

Weight        HB        BP  Result
0     42.0  9.200000  1.375000       0
1     36.0  8.800000  1.500000       0
2     36.0  9.200000  2.125000       0
3     36.0  8.000000  1.375000       0
4     33.0  9.300000  1.571000       0
..     ...       ...       ...     ...
91    55.0  9.000000  1.375000       1
92    39.0  8.400000  1.500000       1
93    50.0  9.072131  1.375000       1
94    38.0  9.072131  1.711841       1
95    50.0  9.000000  1.375000       1

[96 rows x 4 columns]

In [77]:
cols = df.columns.to_list()

In [78]:
# Create training, validation and test splits
df_train = df.sample(frac=0.8, random_state=42)
df_test = df.drop(df_train.index)

df_valid = df_train.sample(frac=0.15, random_state=101)

df_train = df_train.drop(df_valid.index)

print(set(df_train.index).intersection(df_test.index))

df_train.reset_index(drop=True, inplace=True)
df_valid.reset_index(drop=True, inplace=True)
df_test.reset_index(drop=True, inplace=True)

set()


In [79]:
# Sanity check to make sure that there is no row that is in more than one dataframe
df_train.merge(df_valid, how='inner', on=df.columns.to_list())

Empty DataFrame
Columns: [Weight, HB, BP, Result]
Index: []

In [80]:
# Sanity check to make sure that there is no row that is in more than one dataframe
df_train.merge(df_test, how='inner', on=df.columns.to_list())

Weight        HB        BP  Result
0    43.0  9.200000  1.375000       1
1    40.0  9.072131  1.711841       1

In [81]:
df.loc[(df["Weight"] == 43.0) & (df["HB"] == 9.2) & (df["BP"] == 1.375)]

Weight   HB     BP  Result
52    43.0  9.2  1.375       1
78    43.0  9.2  1.375       1

In [82]:
df_test.loc[df_test["Weight"] == 43.0]

Weight   HB     BP  Result
9    43.0  9.2  1.375       1

In [83]:
df_train.loc[df_train["Weight"] == 43.0]

Weight    HB        BP  Result
18    43.0  10.2  1.571429       1
35    43.0   9.2  1.375000       1
44    43.0   9.0  1.666667       1
57    43.0   9.0  1.375000       1
60    43.0   9.0  1.375000       1

In [84]:
# Sanity check to make sure that there is no row that is in more than one dataframe
df_test.merge(df_valid, how='inner', on=df.columns.to_list())

Empty DataFrame
Columns: [Weight, HB, BP, Result]
Index: []

In [85]:
df_train.head()

Weight        HB        BP  Result
0    48.0  9.200000  1.375000       1
1    46.0  9.000000  1.714286       1
2    38.0  9.072131  1.711841       1
3    35.0  8.900000  1.500000       1
4    60.0  9.200000  1.714286       1

In [86]:
# Scale to [0, 1]
max_ = df_train.max(axis=0)
min_ = df_train.min(axis=0)
df_train = (df_train - min_) / (max_ - min_)
df_valid = (df_valid - min_) / (max_ - min_)
df_test = (df_test - min_) / (max_ - min_)

In [87]:
# One-hot encoding as we are using softmax activation function
df_train = pd.get_dummies(df_train, prefix='Result', columns=['Result'])
df_test = pd.get_dummies(df_test, prefix='Result', columns=['Result'])
df_valid = pd.get_dummies(df_valid, prefix='Result', columns=['Result'])

In [88]:
df_train

Weight        HB        BP  Result_0.0  Result_1.0
0   0.514286  0.638298  0.013807           0           1
1   0.457143  0.595745  0.040575           0           1
2   0.228571  0.611092  0.040382           0           1
3   0.142857  0.574468  0.023669           0           1
4   0.857143  0.638298  0.040575           0           1
..       ...       ...       ...         ...         ...
60  0.371429  0.595745  0.013807           0           1
61  0.314286  0.595745  0.013807           0           1
62  0.571429  0.638298  0.029270           0           1
63  0.542857  0.617021  0.029304           0           1
64  0.857143  1.000000  0.013807           0           1

[65 rows x 5 columns]

In [89]:
df_train.loc[df_train["Result_0.0"] == 1]

Weight        HB        BP  Result_0.0  Result_1.0
7   0.342857  0.638298  0.013807           1           0
8   0.228571  0.615691  0.045400           1           0
11  0.285714  0.595745  0.045400           1           0
14  0.171429  0.680851  0.023669           1           0
21  0.171429  0.787234  0.029304           1           0
26  0.142857  0.638298  0.029304           1           0
30  0.428571  0.615691  0.045400           1           0
32  0.000000  0.615691  0.045400           1           0
34  0.171429  0.723404  0.000000           1           0
38  0.085714  0.808511  0.029304           1           0
40  0.171429  0.382979  0.013807           1           0
41  0.285714  0.615691  0.045400           1           0
43  0.000000  0.595745  0.013807           1           0
45  0.028571  0.615691  0.033531           1           0

In [90]:
df_valid

Weight        HB        BP  Result_0.0  Result_1.0
0   0.400000  1.021277  0.029304           0           1
1   0.285714  0.595745  0.013807           0           1
2   0.400000  0.611092  0.040382           0           1
3   0.257143  0.595745  0.013807           1           0
4   0.285714  1.021277  0.001753           0           1
5   0.171429  0.615691  0.045400           1           0
6   0.428571  0.595745  0.013807           0           1
7   0.971429  0.553191  0.036765           0           1
8   0.085714  0.659574  0.029270           1           0
9   0.314286  0.617021  0.013807           0           1
10  0.057143  0.615691  0.045400           1           0
11  0.285714  0.617021  0.029270           0           1

In [91]:
df_test

Weight        HB        BP  Result_0.0  Result_1.0
0   0.171429  0.553191  0.023669           1           0
1   0.171429  0.638298  0.072978           1           0
2   0.171429  0.574468  0.040575           1           0
3   0.171429  0.615691  0.339250           1           0
4   0.171429  0.382979  0.029304           1           0
5   0.171429  0.595745  0.036413           1           0
6   0.857143  0.595745  0.013807           0           1
7   0.714286  0.595745  0.040552           0           1
8   0.285714  0.574468  0.013807           0           1
9   0.371429  0.638298  0.013807           0           1
10  0.285714  0.361702  0.036818           0           1
11  0.600000  0.382979  0.102564           0           1
12  0.742857  0.468085  0.029304           0           1
13  0.571429 -0.063830  0.018033           0           1
14  0.257143  0.611092  0.040382           0           1
15  0.285714  0.611092  0.040382           0           1
16  0.428571  0.611092  0.023669           0           1
17  0.342857  0.611092  0.040382           0           1
18  0.257143  0.468085  0.023669           0           1

In [92]:
df_train.to_csv("train_split.csv", index=False)
df_valid.to_csv("valid_split.csv", index=False)
df_test.to_csv("test_split.csv", index=False)